"""buat table guru

Revision ID: 17e5cb9daae2
Revises: fb1d404c365e
Create Date: 2024-06-07 08:36:33.445102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17e5cb9daae2'
down_revision = 'fb1d404c365e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_guru',
    sa.Column('id_guru', sa.Integer(), nullable=False),
    sa.Column('nama_guru', sa.String(length=100), nullable=False),
    sa.Column('bidang_studi', sa.String(length=100), nullable=True),
    sa.Column('pengalaman_mengajar', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id_guru')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_guru')
    # ### end Alembic commands ###
