"""mengubah table user

Revision ID: 381eef8366d5
Revises: f492bd7f7daf
Create Date: 2024-06-08 23:27:23.188201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '381eef8366d5'
down_revision = 'f492bd7f7daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('level', sa.BigInteger(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('level')

    # ### end Alembic commands ###
