"""buat table kelas

Revision ID: 526beeb39aef
Revises: eccc2d0d3716
Create Date: 2024-06-07 08:43:06.114565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526beeb39aef'
down_revision = 'eccc2d0d3716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_kelas',
    sa.Column('id_kelas', sa.Integer(), nullable=False),
    sa.Column('nama_kelas', sa.String(length=50), nullable=False),
    sa.Column('tingkat_kelas', sa.String(length=10), nullable=True),
    sa.Column('jam_pelajaran', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_kelas')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_kelas')
    # ### end Alembic commands ###
