"""perbarui kelas

Revision ID: 6300dd5a2420
Revises: a2621b4b8bfb
Create Date: 2024-06-24 19:33:40.693560

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6300dd5a2420'
down_revision = 'a2621b4b8bfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deskripsi_mapel', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('topik_mapel', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=True))
        batch_op.drop_column('jam_pelajaran')
        batch_op.drop_column('tingkat_kelas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_kelas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tingkat_kelas', mysql.VARCHAR(length=10), nullable=True))
        batch_op.add_column(sa.Column('jam_pelajaran', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('image')
        batch_op.drop_column('topik_mapel')
        batch_op.drop_column('deskripsi_mapel')

    # ### end Alembic commands ###
