"""perbarui table matapelajaran

Revision ID: a2621b4b8bfb
Revises: 6c73b6685c9a
Create Date: 2024-06-24 14:22:56.139476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2621b4b8bfb'
down_revision = '6c73b6685c9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_matapelajaran', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topik', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('materi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('link_video', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_matapelajaran', schema=None) as batch_op:
        batch_op.drop_column('link_video')
        batch_op.drop_column('materi')
        batch_op.drop_column('topik')

    # ### end Alembic commands ###
