"""buat table Siswa

Revision ID: eccc2d0d3716
Revises: 17e5cb9daae2
Create Date: 2024-06-07 08:41:13.251874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccc2d0d3716'
down_revision = '17e5cb9daae2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_siswa',
    sa.Column('id_siswa', sa.Integer(), nullable=False),
    sa.Column('nama_siswa', sa.String(length=100), nullable=False),
    sa.Column('alamat', sa.String(length=100), nullable=True),
    sa.Column('no_telepon', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('kelas', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_siswa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_siswa')
    # ### end Alembic commands ###
